sudo: required
dist: trusty
language: c
before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y ocaml-nox ocaml-native-compilers camlp4-extra opam
  - opam init -a
  - eval `opam config env`
install:
  - opam install -y deriving lwt
script:
  - make -j2 nc
